# Generated by Django 3.0.6 on 2020-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200602_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sub_line_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
