# Generated by Django 3.0.6 on 2020-06-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_sub_line_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='home_img'),
        ),
    ]
