# Generated by Django 3.0.6 on 2020-06-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abouteme',
            new_name='Aboutme',
        ),
    ]
